In [43]:
import pandas as pd

In [44]:
# df = pd.read_csv("../data/Crimes_-_2001_to_Present_20260303.csv")
# df_sample = df.sample(n=550000, random_state=10)
# df_sample.to_csv("../data/crime_500k.csv", index=False)

In [45]:
df = pd.read_csv("../data/crime_500k.csv")
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [46]:
df.shape

(550000, 22)

In [47]:
df.isnull().sum()

ID                          0
Case Number                 0
Date                        0
Block                       0
IUCR                        0
Primary Type                0
Description                 0
Location Description     1034
Arrest                      0
Domestic                    0
Beat                        0
District                    5
Ward                    39740
Community Area          39673
FBI Code                    0
X Coordinate             6240
Y Coordinate             6240
Year                        0
Updated On                  0
Latitude                 6240
Longitude                6240
Location                 6240
dtype: int64

In [48]:
(df.isnull().sum() / len(df)) * 100

ID                      0.000000
Case Number             0.000000
Date                    0.000000
Block                   0.000000
IUCR                    0.000000
Primary Type            0.000000
Description             0.000000
Location Description    0.188000
Arrest                  0.000000
Domestic                0.000000
Beat                    0.000000
District                0.000909
Ward                    7.225455
Community Area          7.213273
FBI Code                0.000000
X Coordinate            1.134545
Y Coordinate            1.134545
Year                    0.000000
Updated On              0.000000
Latitude                1.134545
Longitude               1.134545
Location                1.134545
dtype: float64

In [49]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12046706,JD227755,05/09/2020 12:35:00 AM,009XX N HARDING AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,False,...,37.0,23.0,08A,1149885.0,1905947.0,2020,05/31/2020 03:40:06 PM,41.897832,-87.724935,"(41.897831506, -87.72493511)"
1,3269498,HK215474,03/02/2004 12:15:00 PM,0000X N WALLER AVE,2024,NARCOTICS,POSS: HEROIN(WHITE),ALLEY,True,False,...,29.0,25.0,18,1138159.0,1899770.0,2004,02/28/2018 03:56:25 PM,41.881101,-87.768154,"(41.881101137, -87.76815352)"
2,1900380,G733028,12/07/2001 11:22:30 AM,011XX N LAWNDALE AV,2095,NARCOTICS,ATTEMPT POSSESSION NARCOTICS,STREET,True,False,...,NaN,NaN,18,1151467.0,1907174.0,2001,08/17/2015 03:03:40 PM,41.901168,-87.719092,"(41.901167583, -87.719092279)"
3,12576708,JE488372,12/24/2021 06:50:00 PM,015XX W FULLERTON AVE,0820,THEFT,$500 AND UNDER,APARTMENT,False,False,...,2.0,7.0,06,1165473.0,1916022.0,2021,12/31/2021 03:40:32 PM,41.925160,-87.667395,"(41.925160357, -87.667394686)"
4,8815299,HV489019,09/22/2012 09:00:00 PM,076XX S MAY ST,0915,MOTOR VEHICLE THEFT,"TRUCK, BUS, MOTOR HOME",STREET,False,False,...,17.0,71.0,07,1169978.0,1854041.0,2012,02/10/2018 03:50:01 PM,41.754982,-87.652646,"(41.754981686, -87.652646228)"

In [50]:
df[["Beat","District"]].head()

   Beat  District
0  1112      11.0
1  1513      15.0
2  1112      11.0
3  1811      18.0
4   612       6.0

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    550000 non-null  int64
 1   Case Number           550000 non-null  object
 2   Date                  550000 non-null  object
 3   Block                 550000 non-null  object
 4   IUCR                  550000 non-null  object
 5   Primary Type          550000 non-null  object
 6   Description           550000 non-null  object
 7   Location Description  548966 non-null  object
 8   Arrest                550000 non-null  bool
 9   Domestic              550000 non-null  bool
 10  Beat                  550000 non-null  int64
 11  District              549995 non-null  float64
 12  Ward                  510260 non-null  float64
 13  Community Area        510327 non-null  float64
 14  FBI Code              550000 non-null  object
 15  X Coordinate          543760 non-null  float64
 16  Y Coordinate          543760 non-null  float64
 17  Year                  550000 non-null  int64
 18  Updated On            550000 non-null  object
 19  Latitude              543760 non-null  float64
 20  Longitude             543760 non-null  float64
 21  Location              543760 non-null  object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 85.0+ MB

In [52]:
df["Location Description"].nunique()

177

In [53]:
df["Location Description"].head(50)

0                          APARTMENT
1                              ALLEY
2                             STREET
3                          APARTMENT
4                             STREET
5                      ATHLETIC CLUB
6                           SIDEWALK
7            RESIDENCE PORCH/HALLWAY
8           SCHOOL, PUBLIC, BUILDING
9                             STREET
10                            STREET
11                         APARTMENT
12                             ALLEY
13                            STREET
14                            STREET
15                            STREET
16    PARKING LOT/GARAGE(NON.RESID.)
17                            STREET
18                            STREET
19                             OTHER
20                         RESIDENCE
21                  RESIDENCE-GARAGE
22                         APARTMENT
23                             OTHER
24           CHA PARKING LOT/GROUNDS
25                         APARTMENT
26                         APARTMENT
27                         RESIDENCE
28                         APARTMENT
29                            STREET
30                          SIDEWALK
31                         APARTMENT
32                          SIDEWALK
33                            STREET
34                  RESIDENCE-GARAGE
35                            STREET
36                     BAR OR TAVERN
37           RESIDENCE PORCH/HALLWAY
38                         APARTMENT
39                     PARK PROPERTY
40                GROCERY FOOD STORE
41                     ATHLETIC CLUB
42                             OTHER
43                         RESIDENCE
44                         APARTMENT
45                         RESIDENCE
46                         RESIDENCE
47                         RESIDENCE
48                            STREET
49                         RESIDENCE
Name: Location Description, dtype: object

In [54]:
df["Description"].unique()

array(['SIMPLE', 'POSS: HEROIN(WHITE)', 'ATTEMPT POSSESSION NARCOTICS',
       '$500 AND UNDER', 'TRUCK, BUS, MOTOR HOME',
       'ATTEMPT POSSESSION CANNABIS', 'POSS: CANNABIS 30GMS OR LESS',
       'FOUND SUSPECT NARCOTICS', 'AUTOMOBILE',
       'MANUFACTURE / DELIVER - CANNABIS OVER 10 GRAMS',
       'DOMESTIC BATTERY SIMPLE', 'TO VEHICLE', 'OVER $500',
       'BURGLARY FROM MOTOR VEHICLE', 'MANU/DELIVER: HEROIN (WHITE)',
       'RETAIL THEFT', 'TO PROPERTY', 'TO STATE SUP LAND',
       'FINANCIAL ID THEFT: OVER $300', 'POSS: CRACK',
       'THEFT FROM MOTOR VEHICLE', 'TO LAND', 'CRIMINAL DEFACEMENT',
       'TO RESIDENCE', 'FROM BUILDING', 'RESIST/OBSTRUCT/DISARM OFFICER',
       'RECKLESS CONDUCT', 'AGGRAVATED: OTHER DANG WEAPON',
       'FORCIBLE ENTRY', 'ILLEGAL USE CASH CARD', 'AGGRAVATED - HANDGUN',
       'COUNTERFEIT CHECK',
       'AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON',
       'TELEPHONE THREAT', 'POSSESS - HEROIN (WHITE)',
       'AGG CRIMINAL SEXUAL ABUSE', 'UNLAWFUL ENTRY', 'AGGRAVATED',
       'STRONG ARM - NO WEAPON', 'POCKET-PICKING', 'POSS: COCAINE',
       'HARASSMENT BY TELEPHONE', 'LIQUOR LICENSE VIOLATION',
       'FINANCIAL IDENTITY THEFT OVER $ 300',
       'ATTEMPT: CYCLE, SCOOTER, BIKE W-VIN', 'FRAUD OR CONFIDENCE GAME',
       'CREDIT CARD FRAUD', 'STRONGARM - NO WEAPON',
       'PRO EMP HANDS NO/MIN INJURY', 'UNLAWFUL POSS OF HANDGUN',
       'VIOLATE ORDER OF PROTECTION', 'SOLICIT NARCOTICS ON PUBLICWAY',
       'OBSTRUCTING IDENTIFICATION',
       'AGGRAVATED - KNIFE / CUTTING INSTRUMENT', 'FIRST DEGREE MURDER',
       'FINANCIAL IDENTITY THEFT $300 AND UNDER',
       'FINANCIAL ID THEFT:$300 &UNDER', 'RECKLESS FIREARM DISCHARGE',
       'AGGRAVATED: HANDGUN', 'PAY TV SERVICE OFFENSES',
       'SOLICIT ON PUBLIC WAY', 'OTHER VEHICLE OFFENSE',
       'AGGRAVATED:KNIFE/CUTTING INSTR', 'UNLAWFUL USE OTHER DANG WEAPON',
       'CHILD ABUSE',
       'AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SERIOUS INJURY',
       'ARMED: HANDGUN', 'THEFT / RECOVERY - AUTOMOBILE',
       'AGG PO HANDS NO/MIN INJURY', 'THEFT OF LOST/MISLAID PROP',
       'TO STATE SUP PROP', 'NON-AGGRAVATED',
       'SEX OFFENDER: FAIL REG NEW ADD',
       'AGGRAVATED - OTHER DANGEROUS WEAPON', 'POSSESS - CRACK',
       'HARASSMENT BY ELECTRONIC MEANS', 'MANUFACTURE / DELIVER - CRACK',
       'THEFT OF LOST / MISLAID PROPERTY', 'POSS: BARBITUATES',
       'ATTEMPT - AUTOMOBILE', 'ARSON THREAT', 'HOME INVASION',
       'ILLEGAL CONSUMPTION BY MINOR', 'THEFT/RECOVERY: AUTOMOBILE',
       'ILLEGAL POSSESSION CASH CARD',
       'NON-CONSENSUAL DISSEMINATION OF PRIVATE SEXUAL IMAGES',
       'LICENSE VIOLATION', 'PURSE-SNATCHING', 'THEFT OF LABOR/SERVICES',
       'VEHICULAR HIJACKING', 'ATT CRIM SEXUAL ABUSE',
       'AGG CRIM SEX ABUSE FAM MEMBER', 'INTIMIDATION',
       'SOLICIT FOR PROSTITUTE', 'GAME/DICE', 'OTHER WEAPONS VIOLATION',
       'ARMED:KNIFE/CUTTING INSTRUMENT', 'ARMED: OTHER DANGEROUS WEAPON',
       'MANU/DEL:CANNABIS OVER 10 GMS', 'FALSE/STOLEN/ALTERED TRP',
       'VEHICLE TITLE/REG OFFENSE', 'AGGRAVATED PO: OTHER DANG WEAP',
       'ATTEMPT ARSON', 'ATTEMPT FORCIBLE ENTRY', 'AGGRAVATED: OTHER',
       'ARMED - KNIFE / CUTTING INSTRUMENT', 'ATTEMPT THEFT',
       'POSSESSION OF DRUG EQUIPMENT', 'MANU/DEL:CANNABIS 10GM OR LESS',
       'FALSE FIRE ALARM', 'STOLEN PROP: BUY/RECEIVE/POS.',
       'PUBLIC AID WIRE/MAIL FRAUD - VIA MAIL/PACKAGE/DELIVERY SYS',
       'BOGUS CHECK', 'OTHER CRIME INVOLVING PROPERTY',
       'THEFT OF LABOR / SERVICES', 'TO CITY OF CHICAGO PROPERTY',
       'AGG: HANDS/FIST/FEET NO/MINOR INJURY', 'PREDATORY',
       'ARMED - HANDGUN', 'CRIMINAL SEXUAL ABUSE', 'PAROLE VIOLATION',
       'AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
       'ATT: AUTOMOBILE',
       'AGGRAVATED DOMESTIC BATTERY: HANDS/FIST/FEET SERIOUS INJURY',
       'AGGRAVATED POLICE OFFICER - HANDGUN', 'POSSESS - COCAINE',
       'COUNTERFEITING DOCUMENT', 'ENDANGERING LIFE/HEALTH CHILD',
       'UNLAWFUL USE/SALE AIR RIFLE', 'UNLAWFUL USE - HANDGUN',
       'PROTECTED EMPLOYEE - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'SEX OFFENDER: FAIL TO REGISTER', 'OBSCENE TELEPHONE CALLS',
       'SOLICIT FOR BUSINESS', 'MANU/DELIVER:CRACK',
       'PATRONIZING A PROSTITUTE', 'DELIVER CANNABIS TO PERSON UNDER 18',
       'AGGRAVATED VEHICULAR HIJACKING', 'ATTEMPT NON-AGGRAVATED',
       'ATTEMPT: ARMED-HANDGUN',
       'AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST',
       'ATTEMPT FINANCIAL IDENTITY THEFT',
       'UNLAWFUL USE - OTHER DANGEROUS WEAPON',
       'UNLAWFUL POSSESSION - HANDGUN', 'CYCLE, SCOOTER, BIKE W-VIN',
       'AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING INSTRUMENT',
       'OTHER OFFENSE', 'CHILD ABDUCTION/STRANGER', 'PUBLIC INDECENCY',
       'POSS: CANNABIS MORE THAN 30GMS', 'HARBOR RUNAWAY',
       'DELIVERY CONTAINER THEFT', 'FORFEIT PROPERTY',
       'AGG SEX ASSLT OF CHILD FAM MBR', 'UNLAWFUL USE - OTHER FIREARM',
       'BY FIRE', 'ATTEMPT: STRONGARM-NO WEAPON', 'FORGERY',
       'VEHICLE TITLE / REGISTRATION OFFENSE', 'FALSE POLICE REPORT',
       'SEXUAL EXPLOITATION OF A CHILD',
       'MANUFACTURE / DELIVER -  HEROIN (WHITE)',
       'UNLAWFUL VISITATION INTERFERENCE', 'FALSE / STOLEN / ALTERED TRP',
       'POSS: SYNTHETIC DRUGS', 'POSS: PCP', 'ANIMAL ABUSE / NEGLECT',
       'AGGRAVATED - OTHER FIREARM', 'VIO BAIL BOND: DOM VIOLENCE',
       'BOMB THREAT', 'ILLEGAL POSSESSION BY MINOR',
       'AGG: HANDS/FIST/FEET SERIOUS INJURY', 'AGG: FINANCIAL ID THEFT',
       'KEEP PLACE OF PROSTITUTION', 'POSS: HEROIN(BRN/TAN)',
       'SOLICITATION OF A SEXUAL ACT', 'AGGRAVATED OF A SENIOR CITIZEN',
       'FROM COIN-OPERATED MACHINE OR DEVICE', 'POSSESS - HALLUCINOGENS',
       'ARMED WHILE UNDER THE INFLUENCE', 'UNLAWFUL USE HANDGUN',
       'CHILD ABDUCTION', 'GUN OFFENDER - DUTY TO REGISTER',
       'NON-CONSENSUAL DISSEMINATION PRIVATE SEXUAL IMAGES',
       'UNLAWFUL POSSESSION - OTHER FIREARM', 'POSSESS - METHAMPHETAMINE',
       'ATTEMPT - FINANCIAL IDENTITY THEFT',
       'AGGRAVATED CRIMINAL SEXUAL ABUSE',
       'UNLAWFUL USE OF RECORDED SOUND', 'CHILD ABANDONMENT',
       'COMPUTER FRAUD', 'UNLAWFUL POSS OTHER FIREARM',
       'MANU/DELIVER:AMPHETAMINES', 'THEFT BY LESSEE, MOTOR VEHICLE',
       'AGGRAVATED PO: HANDGUN', 'AGGRAVATED: OTHER FIREARM',
       'ATTEMPT: ARMED-KNIFE/CUT INSTR',
       'AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS WEAPON',
       'AGG PRO.EMP: OTHER DANG WEAPON',
       'POSSESS - CANNABIS MORE THAN 30 GRAMS', 'PROBATION VIOLATION',
       'OTHER CRIME AGAINST PERSON', 'UNLAWFUL POSS AMMUNITION',
       'AGGRAVATED POLICE OFFICER - OTHER DANGEROUS WEAPON',
       'STOLEN PROPERTY BUY / RECEIVE / POSSESS',
       'THEFT BY LESSEE,MOTOR VEH', 'POSS FIREARM/AMMO:NO FOID CARD',
       'AGGRAVATED FINANCIAL IDENTITY THEFT',
       'CONTRIBUTE CRIM DELINQUENCY JUVENILE',
       'AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'AGG PRO.EMP: HANDGUN', 'SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
       'MOB ACTION', 'CYCLE, SCOOTER, BIKE WITH VIN',
       'ENDANGERING LIFE / HEALTH OF CHILD', 'UNLAWFUL RESTRAINT',
       'INSTITUTIONAL VANDALISM', 'ATTEMPT - TRUCK, BUS, MOTOR HOME',
       'AGGRAVATED - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'ANIMAL ABUSE/NEGLECT', 'POS: HYPODERMIC NEEDLE',
       'SEX OFFENDER - FAIL TO REGISTER', 'POSS: HALLUCINOGENS',
       'UNLAWFUL USE OTHER FIREARM', 'GUN OFFENDER - ANNUAL REGISTRATION',
       'AGG. PROTECTED EMPLOYEE - HANDS, FISTS, FEET, SERIOUS INJURY',
       'CRIM SEX ABUSE BY FAM MEMBER',
       'AGGRAVATED DOMESTIC BATTERY: OTHER DANGEROUS WEAPON',
       'SEX OFFENDER - FAIL TO REGISTER NEW ADDRESS',
       'ARMED - OTHER FIREARM',
       'AGGRAVATED POLICE OFFICER - HANDS, FISTS, FEET, NO INJURY',
       'OTHER VIOLATION', 'IMPERSONATION', 'CRIMINAL DRUG CONSPIRACY',
       'GUN OFFENDER: ANNUAL REGISTRATION',
       'SEX ASSLT OF CHILD BY FAM MBR', 'CALL OPERATION',
       'GUN OFFENDER: DUTY TO REGISTER',
       'VIOLATION OF CIVIL NO CONTACT ORDER',
       'AGGRAVATED DOMESTIC BATTERY: OTHER FIREARM',
       'ATT AGG CRIMINAL SEXUAL ABUSE',
       'ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT',
       'TO STATE SUPPORTED PROPERTY', 'MANU/DELIVER:COCAINE',
       'FINAN EXPLOIT-ELDERLY/DISABLED', 'CONCEALING/AIDING A FUGITIVE',
       'UNLAWFUL USE OF A COMPUTER', 'THEFT/RECOVERY: TRUCK,BUS,MHOME',
       'FORCIBLE DETENTION', 'UNLAWFUL POSSESSION - AMMUNITION',
       'SALE/DEL HYPODERMIC NEEDLE', 'AGGRAVATED - OTHER', 'OTHER',
       'AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
       'AGGRAVATED DOMESTIC BATTERY', 'TIRE DEFLATION DEVICE DEPLOYMENT',
       'ATTEMPT - CYCLE, SCOOTER, BIKE WITH VIN',
       'MANU/DELIVER:HEROIN(BLACK TAR)', 'CHILD PORNOGRAPHY',
       'POSSESS - SYNTHETIC DRUGS',
       'AGGRAVATED PROTECTED EMPLOYEE - OTHER DANGEROUS WEAPON',
       'OBSCENE MATTER', 'UNLAWFUL INTERFERE/VISITATION',
       'MANU/DELIVER: HALLUCINOGEN', 'CONTRIBUTE DELINQUENCY OF A CHILD',
       'THEFT / RECOVERY - TRUCK, BUS, MOBILE HOME',
       'AGGRAVATED - HANDS, FISTS, FEET, SERIOUS INJURY', 'LOOTING',
       'INTERFERENCE JUDICIAL PROCESS', 'KIDNAPPING',
       'ATT: TRUCK, BUS, MOTOR HOME',
       'AGGRAVATED PROTECTED EMPLOYEE - HANDGUN',
       'AGGRAVATED: KNIFE/CUT INSTR', 'MANU/DELIVER:SYNTHETIC DRUGS',
       'GAME/CARDS', 'OBSTRUCTING JUSTICE', 'CYCLE, SCOOTER, BIKE NO VIN',
       'THEFT BY LESSEE,NON-VEH', 'AGGRAVATED COMPUTER TAMPERING',
       'ESCAPE', 'POSSESS - BARBITURATES',
       'VIOLATION GPS MONITORING DEVICE',
       'ATTEMPT STRONG ARM - NO WEAPON', 'ATTEMPT ARMED - HANDGUN',
       'ATTEMPT CRIMINAL SEXUAL ABUSE',
       'INDECENT SOLICITATION OF A CHILD', 'OBSTRUCTING SERVICE',
       'ARMED - OTHER DANGEROUS WEAPON',
       'RESIST / OBSTRUCT / DISARM OFFICER',
       'FINANCIAL EXPLOITATION OF AN ELDERLY OR DISABLED PERSON',
       'PANDERING', 'POSS: AMPHETAMINES', 'SELL/GIVE/DEL LIQUOR TO MINOR',
       'CONTRIBUTE TO THE DELINQUENCY OF CHILD', 'AGGRAVATED OF A CHILD',
       'UNLAWFUL USE / SALE OF AIR RIFLE',
       'THEFT/RECOVERY: CYCLE, SCOOTER, BIKE NO VIN',
       'GAME/AMUSEMENT DEVICE', 'OTHER PROSTITUTION OFFENSE',
       'INTOXICATING COMPOUNDS', 'UNIDENTIFIABLE RECORDING SOUND',
       'DECEPTIVE COLLECTION PRACTICES', 'ATTEMPT: ARMED-OTHER DANG WEAP',
       'POSSESS - CANNABIS 30 GRAMS OR LESS',
       'CHILD ABDUCTION / STRANGER', 'UNLAWFUL SALE HANDGUN',
       'POSSESS - HEROIN (TAN / BROWN TAR)', 'POSSESS - AMPHETAMINES',
       'ALTER/FORGE PRESCRIPTION', 'PUBLIC DEMONSTRATION',
       'ARMED: OTHER FIREARM', 'INSURANCE FRAUD',
       'VIOLATION OF SUMMARY CLOSURE',
       'GUN OFFENDER: DUTY TO REPORT CHANGE OF INFORMATION',
       'POSSESSION OF BURGLARY TOOLS', 'AGGRAVATED PO: KNIFE/CUT INSTR',
       'UNAUTHORIZED VIDEOTAPING', 'ATTEMPT AGG: OTHER DANG WEAPON',
       'SALE TOBACCO PRODUCTS TO MINOR', 'SEXUAL RELATIONS IN FAMILY',
       'OTHER ARSON/EXPLOSIVE INCIDENT',
       'ATTEMPT ARMED - OTHER DANGEROUS WEAPON', 'PIMPING',
       'THEFT/RECOVERY: CYCLE, SCOOTER, BIKE W-VIN',
       'MANU/DELIVER: HEROIN(BRN/TAN)', 'ANIMAL FIGHTING',
       'ATTEMPT AGGRAVATED', 'CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
       'BOARD PLANE WITH WEAPON', 'FROM COIN-OP MACHINE/DEVICE',
       'SALE/DIST OBSCENE MAT TO MINOR', 'PEEPING TOM',
       'ATTEMPT AGG: OTHER', 'POSS: HEROIN(BLACK TAR)',
       'ATTEMPT AGGRAVATED CRIMINAL SEXUAL ABUSE',
       'SOLICIT NARCOTICS ON PUBLIC WAY', 'EXTORTION',
       'HAZARDOUS MATERIALS VIOLATION',
       'AGGRAVATED DOMESTIC BATTERY - HANDGUN', 'ATTEMPT: AGGRAVATED',
       'ATTEMPT: ARMED-OTHER FIREARM', 'AGGRAVATED PO: OTHER FIREARM',
       'POS: PORNOGRAPHIC PRINT', 'EMBEZZLEMENT',
       'FIREARM REGISTRATION VIOLATION', 'CRIMINAL TRANSMISSION OF HIV',
       'OBSCENITY', 'AGGRAVATED PO:KNIFE/CUT INSTR',
       'POST GRAPHIC INFO PORGNOGRAPHIC INTERNET OR POSS GRAPHIC INF',
       'PROHIBITED PLACES', 'POSSESS - PCP', 'STATE BENEFITS FRAUD',
       'AGG PO HANDS ETC SERIOUS INJ',
       'VIOLENT OFFENDER: ANNUAL REGISTRATION',
       'AGG PRO EMP HANDS SERIOUS INJ', 'CYBERSTALKING',
       'SEX OFFENDER - PROHIBITED ZONE',
       'MANUFACTURE / DELIVER - SYNTHETIC DRUGS',
       'INTERNET OFFENSES - ELECTRONIC FENCING',
       'TO FIRE FIGHT.APP.EQUIP', 'MANU/DELIVER:PCP', 'TO AIRPORT',
       'AGGRAVATED DOMESTIC BATTERY: HANDGUN', 'WIC FRAUD',
       'INVOLUNTARY SERVITUDE', 'MONEY LAUNDERING',
       'INDECENT SOLICITATION/CHILD', 'TAMPER WITH MOTOR VEHICLE',
       'MANUFACTURE / DELIVER - COCAINE', 'POSS: METHAMPHETAMINES',
       'UNLAWFUL SALE/DELIVERY OF FIREARM AT SCHOOL', 'LICENSED PREMISE',
       'ILLEGAL ILL LOTTERY', 'VIOLATION OF STALKING NO CONTACT ORDER',
       'MANUFACTURE / DELIVER - PCP',
       'AGGRAVATED P.O. - HANDS, FISTS, FEET, SERIOUS INJURY',
       'INDECENT SOLICITATION/ADULT',
       'AGGRAVATED PROTECTED EMPLOYEE - OTHER FIREARM',
       'POS: EXPLOSIVE/INCENDIARY DEV',
       'VIOLATION OF BAIL BOND - DOMESTIC VIOLENCE',
       'SOLICIT OFF PUBLIC WAY', 'BY EXPLOSIVE',
       'MANUFACTURE / DELIVER - CANNABIS 10 GRAMS OR LESS',
       'AGGRAVATED PROTECTED EMPLOYEE - KNIFE / CUTTING INSTRUMENT',
       'POSSESS FIREARM / AMMUNITION - NO FOID CARD',
       'VIOLATION OF SMOKING BAN', 'MANU/DELIVER:BARBITUATES',
       'MANU/DELIVER: METHAMPHETAMINES', 'AGG RITUAL MUT:OTH DANG WEAPON',
       'VIOLENT OFFENDER - ANNUAL REGISTRATION',
       'ARSONIST - ANNUAL REGISTRATION',
       'CONTRIBUTE TO THE CRIMINAL DELINQUENCY OF CHILD',
       'ATTEMPT AGG: HANDGUN', 'AGG PRO.EMP:KNIFE/CUTTING INST',
       'POS: CHEMICAL/DRY-ICE DEVICE',
       'VIOLENT OFFENDER - DUTY TO REGISTER',
       'GUN OFFENDER - DUTY TO REPORT CHANGE OF INFORMATION',
       'MANUFACTURE / DELIVER - HALLUCINOGEN', 'RECKLESS HOMICIDE',
       'ATTEMPT ARMED - OTHER FIREARM', 'LIBRARY THEFT', 'CANNABIS PLANT',
       'VIOLENT OFFENDER - FAIL TO REGISTER NEW ADDRESS',
       'ABUSE / NEGLECT - CARE FACILITY',
       'SELL / GIVE / DELIVER LIQUOR TO MINOR',
       'AGG PRO.EMP: OTHER FIREARM', 'POSS: LOOK-ALIKE DRUGS',
       'REFUSING TO AID AN OFFICER', 'EAVESDROPPING', 'BRIBERY',
       'COMMERCIAL SEX ACTS', 'POSS. KEYS OR DEV.TO COIN MACH',
       'SEX OFFENDER: PROHIBITED ZONE',
       'MINOR DISSEMINATE INDECENT DEPICT ANOTHER MINOR ELEC DEVICE',
       'CONT SUBS:FAIL TO MAINT RECORD',
       'VIOLENT OFFENDER: DUTY TO REGISTER',
       'DEFACE IDENT MARKS OF FIREARM',
       'SALE / DELIVER - DRUG PARAPHERNALIA',
       'VIOLENT OFFENDER: FAIL TO REGISTER NEW ADDRESS',
       'POSSESSION - EXPLOSIVE / INCENDIARY DEVICE',
       'THEFT BY LESSEE, NON-MOTOR VEHICLE', 'BOOKMAKING/SPORTS',
       'SOLICITING FOR A PROSTITUTE', 'ATTEMPT AGG: KNIFE/CUT INSTR',
       'UNLAWFUL SALE OTHER FIREARM', 'MANU/DELIVER:LOOK-ALIKE DRUG',
       'WIREROOM/SPORTS', 'OTHER ARSON / EXPLOSIVE INCIDENT',
       'SALE/DEL DRUG PARAPHERNALIA', 'DELIVER CANNABIS TO PERSON <18',
       'SEX RELATION IN FAMILY', 'IN TAVERN', 'MINOR MISREPRESENT AGE',
       'ABUSE/NEGLECT: CARE FACILITY',
       'MANUFACTURE / DELIVER - METHAMPHETAMINE',
       'UNAUTH VIDEO RECORD/TRANSMIT LIVE VIDEO UNDER/THRU CLOTHES',
       'ARMED VIOLENCE', 'CRIMINAL SEXUAL ABUSE - SEXUAL PENETRATION',
       'PBLC AID WIRE AND MAIL FRAUD- UNLAW OBT PBLC AID',
       'SOLICITING FOR BUSINESS', 'ATTEMPT AGGRAVATED - OTHER',
       'DEL CONT SUBS TO PERSON <18', 'BOLITA OR BOLI PUL/RUNNER',
       'MANUFACTURE / DELIVER - BARBITURATES',
       'POSSESSION: SYNTHETIC MARIJUANA',
       'ATTEMPT AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
       'CALCULATED CANNABIS CONSPIRACY', 'INTERFERE W/ EMERGENCY EQUIP',
       'AGGRAVATED OF AN UNBORN CHILD',
       'POSSESSION OF PORNOGRAPHIC PRINT',
       'INDECENT SOLICITATION OF AN ADULT', 'SELL/ADVERTISE FIREWORKS',
       'LIBRARY VANDALISM', 'GAME / AMUSEMENT DEVICE',
       'AGGRAVATED OF A UNBORN CHILD',
       'INTERFERE WITH EMERGENCY EQUIPMENT',
       'AGGRAVATED POLICE OFFICER - KNIFE / CUTTING INSTRUMENT',
       'COMPELLING ORG MEMBERSHIP',
       'SALE / DISTRIBUTE OBSCENE MATERIAL TO MINOR',
       'MANUFACTURE / DELIVER - HEROIN (TAN / BROWN TAR)',
       'INTERFERE W/ HIGHER EDUCATION',
       'DISCLOSE DOMESTIC VIOLENCE VICTIM LOCATION',
       'THEFT / RECOVERY - CYCLE, SCOOTER, BIKE WITH VIN',
       'OF UNBORN CHILD', 'UNLAWFUL SALE - HANDGUN', 'JUVENILE PIMPING',
       'ADULTRY', 'OVER $300', 'ALTER / FORGE PRESCRIPTION',
       'EDUCATIONAL INTIMIDAITON', 'OF AN UNBORN CHILD',
       'ATTEMPT AGGRAVATED - HANDGUN',
       'PLACE VIDEO RECORD/TRANSMIT DEVICE - RESTROOM/TAN SALON/CHNG',
       'UNLAWFUL SALE - DELIVERY OF FIREARM AT SCHOOL',
       'ATT AGG CRIM SEXUAL ABUSE', 'COMPOUNDING A CRIME',
       'AGGRAVATED PO: OTHER DANGEROUS WEAPON', '$300 AND UNDER',
       'FINANCIAL IDENTITY THEFT: OVER $300',
       'MANU/POSS. W/INTENT TO DELIVER: SYNTHETIC MARIJUANA',
       'WIREROOM/HORSES', 'CONCEALED CARRY LICENSE REVOCATION',
       'AGGRAVATED: HANDS / FIST / FEET SERIOUS INJURY', 'BIGAMY',
       'OFFICIAL MISCONDUCT'], dtype=object)

In [55]:
df["Block"].unique()

array(['009XX N HARDING AVE', '0000X N WALLER AVE', '011XX N LAWNDALE AV',
       ..., '007XX W CORNELIA AV', '056XX S Dorchester Ave',
       '043XX W HADDON AV'], shape=(42847,), dtype=object)

In [56]:
df.dropna(subset=["District", "Ward", "Community Area", "Latitude", "Longitude"], inplace=True)

In [57]:
df.shape

(504569, 22)

In [58]:
df.isnull().sum()

ID                        0
Case Number               0
Date                      0
Block                     0
IUCR                      0
Primary Type              0
Description               0
Location Description    680
Arrest                    0
Domestic                  0
Beat                      0
District                  0
Ward                      0
Community Area            0
FBI Code                  0
X Coordinate              0
Y Coordinate              0
Year                      0
Updated On                0
Latitude                  0
Longitude                 0
Location                  0
dtype: int64

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 504569 entries, 0 to 549999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    504569 non-null  int64
 1   Case Number           504569 non-null  object
 2   Date                  504569 non-null  object
 3   Block                 504569 non-null  object
 4   IUCR                  504569 non-null  object
 5   Primary Type          504569 non-null  object
 6   Description           504569 non-null  object
 7   Location Description  503889 non-null  object
 8   Arrest                504569 non-null  bool
 9   Domestic              504569 non-null  bool
 10  Beat                  504569 non-null  int64
 11  District              504569 non-null  float64
 12  Ward                  504569 non-null  float64
 13  Community Area        504569 non-null  float64
 14  FBI Code              504569 non-null  object
 15  X Coordinate          504569 non-null  float64
 16  Y Coordinate          504569 non-null  float64
 17  Year                  504569 non-null  int64
 18  Updated On            504569 non-null  object
 19  Latitude              504569 non-null  float64
 20  Longitude             504569 non-null  float64
 21  Location              504569 non-null  object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 81.8+ MB

In [60]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

C:\Users\HopeR\AppData\Local\Temp\ipykernel_16844\3693147909.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [61]:
df["Date"].isnull().sum()

np.int64(0)

In [62]:
df["Hour"] = df["Date"].dt.hour
df["Day"] = df["Date"].dt.day
df["Day_of_Week"] = df["Date"].dt.dayofweek
df["Month"] = df["Date"].dt.month
df["Is_Weekend"] = df["Day_of_Week"].isin([5,6]).astype(int)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 504569 entries, 0 to 549999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    504569 non-null  int64
 1   Case Number           504569 non-null  object
 2   Date                  504569 non-null  datetime64[ns]
 3   Block                 504569 non-null  object
 4   IUCR                  504569 non-null  object
 5   Primary Type          504569 non-null  object
 6   Description           504569 non-null  object
 7   Location Description  503889 non-null  object
 8   Arrest                504569 non-null  bool
 9   Domestic              504569 non-null  bool
 10  Beat                  504569 non-null  int64
 11  District              504569 non-null  float64
 12  Ward                  504569 non-null  float64
 13  Community Area        504569 non-null  float64
 14  FBI Code              504569 non-null  object
 15  X Coordinate          504569 non-null  float64
 16  Y Coordinate          504569 non-null  float64
 17  Year                  504569 non-null  int64
 18  Updated On            504569 non-null  object
 19  Latitude              504569 non-null  float64
 20  Longitude             504569 non-null  float64
 21  Location              504569 non-null  object
 22  Hour                  504569 non-null  int32
 23  Day                   504569 non-null  int32
 24  Day_of_Week           504569 non-null  int32
 25  Month                 504569 non-null  int32
 26  Is_Weekend            504569 non-null  int64
dtypes: bool(2), datetime64[ns](1), float64(7), int32(4), int64(4), object(9)
memory usage: 93.4+ MB

In [64]:
df["Arrest"] = df["Arrest"].astype(int)
df["Domestic"] = df["Domestic"].astype(int)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 504569 entries, 0 to 549999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    504569 non-null  int64
 1   Case Number           504569 non-null  object
 2   Date                  504569 non-null  datetime64[ns]
 3   Block                 504569 non-null  object
 4   IUCR                  504569 non-null  object
 5   Primary Type          504569 non-null  object
 6   Description           504569 non-null  object
 7   Location Description  503889 non-null  object
 8   Arrest                504569 non-null  int64
 9   Domestic              504569 non-null  int64
 10  Beat                  504569 non-null  int64
 11  District              504569 non-null  float64
 12  Ward                  504569 non-null  float64
 13  Community Area        504569 non-null  float64
 14  FBI Code              504569 non-null  object
 15  X Coordinate          504569 non-null  float64
 16  Y Coordinate          504569 non-null  float64
 17  Year                  504569 non-null  int64
 18  Updated On            504569 non-null  object
 19  Latitude              504569 non-null  float64
 20  Longitude             504569 non-null  float64
 21  Location              504569 non-null  object
 22  Hour                  504569 non-null  int32
 23  Day                   504569 non-null  int32
 24  Day_of_Week           504569 non-null  int32
 25  Month                 504569 non-null  int32
 26  Is_Weekend            504569 non-null  int64
dtypes: datetime64[ns](1), float64(7), int32(4), int64(6), object(9)
memory usage: 100.1+ MB

In [66]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Year,Updated On,Latitude,Longitude,Location,Hour,Day,Day_of_Week,Month,Is_Weekend
0,12046706,JD227755,2020-05-09 00:35:00,009XX N HARDING AVE,0560,ASSAULT,SIMPLE,APARTMENT,0,0,...,2020,05/31/2020 03:40:06 PM,41.897832,-87.724935,"(41.897831506, -87.72493511)",0,9,5,5,1
1,3269498,HK215474,2004-03-02 12:15:00,0000X N WALLER AVE,2024,NARCOTICS,POSS: HEROIN(WHITE),ALLEY,1,0,...,2004,02/28/2018 03:56:25 PM,41.881101,-87.768154,"(41.881101137, -87.76815352)",12,2,1,3,0
3,12576708,JE488372,2021-12-24 18:50:00,015XX W FULLERTON AVE,0820,THEFT,$500 AND UNDER,APARTMENT,0,0,...,2021,12/31/2021 03:40:32 PM,41.925160,-87.667395,"(41.925160357, -87.667394686)",18,24,4,12,0
4,8815299,HV489019,2012-09-22 21:00:00,076XX S MAY ST,0915,MOTOR VEHICLE THEFT,"TRUCK, BUS, MOTOR HOME",STREET,0,0,...,2012,02/10/2018 03:50:01 PM,41.754982,-87.652646,"(41.754981686, -87.652646228)",21,22,5,9,1
5,7416305,HS217607,2010-03-20 11:00:00,0000X S STATE ST,0820,THEFT,$500 AND UNDER,ATHLETIC CLUB,0,0,...,2010,02/10/2018 03:50:01 PM,41.881666,-87.627761,"(41.881666323, -87.627760999)",11,20,5,3,1

In [67]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location', 'Hour', 'Day', 'Day_of_Week', 'Month', 'Is_Weekend'],
      dtype='object')

In [68]:
df["Primary Type"].value_counts()

Primary Type
THEFT                                107266
BATTERY                               92045
CRIMINAL DAMAGE                       57405
NARCOTICS                             44644
ASSAULT                               34207
OTHER OFFENSE                         31806
BURGLARY                              26653
MOTOR VEHICLE THEFT                   25830
DECEPTIVE PRACTICE                    23097
ROBBERY                               18860
CRIMINAL TRESPASS                     13637
WEAPONS VIOLATION                      7880
PROSTITUTION                           4032
OFFENSE INVOLVING CHILDREN             3580
PUBLIC PEACE VIOLATION                 3316
SEX OFFENSE                            2031
CRIM SEXUAL ASSAULT                    1503
INTERFERENCE WITH PUBLIC OFFICER       1327
HOMICIDE                                917
LIQUOR LAW VIOLATION                    858
ARSON                                   824
GAMBLING                                814
CRIMINAL SEXUAL ASSAULT                 728
KIDNAPPING                              418
STALKING                                391
INTIMIDATION                            299
CONCEALED CARRY LICENSE VIOLATION       108
OBSCENITY                                66
PUBLIC INDECENCY                         11
HUMAN TRAFFICKING                         9
OTHER NARCOTIC VIOLATION                  5
RITUALISM                                 1
NON-CRIMINAL                              1
Name: count, dtype: int64

In [69]:
df.groupby('Month').size()

Month
1     38559
2     34283
3     39278
4     40226
5     45570
6     45035
7     47833
8     47021
9     44269
10    44809
11    39678
12    38008
dtype: int64

In [70]:
df['Arrest'].value_counts()

Arrest
0    379385
1    125184
Name: count, dtype: int64

In [71]:
severity_map = {
    'HOMICIDE': 4,
    'CRIM SEXUAL ASSAULT': 4,
    'CRIMINAL SEXUAL ASSAULT': 4,
    'HUMAN TRAFFICKING': 4,
    'KIDNAPPING': 4,

    'ASSAULT': 3,
    'BATTERY': 3,
    'ROBBERY': 3,
    'WEAPONS VIOLATION': 3,
    'OFFENSE INVOLVING CHILDREN': 3,
    'STALKING': 3,
    'INTIMIDATION': 3,
    'ARSON': 3,
    'SEX OFFENSE': 3,

    'BURGLARY': 2,
    'MOTOR VEHICLE THEFT': 2,
    'CRIMINAL DAMAGE': 2,
    'THEFT': 2,
    'DECEPTIVE PRACTICE': 2,
    'CRIMINAL TRESPASS': 2,
    'OTHER OFFENSE': 2,
    'NARCOTICS': 2,
    'OTHER NARCOTIC VIOLATION': 2,
    'INTERFERENCE WITH PUBLIC OFFICER': 2,
    'CONCEALED CARRY LICENSE VIOLATION': 2,

    'PROSTITUTION': 1,
    'PUBLIC PEACE VIOLATION': 1,
    'LIQUOR LAW VIOLATION': 1,
    'GAMBLING': 1,
    'PUBLIC INDECENCY': 1,
    'OBSCENITY': 1,
    'NON-CRIMINAL': 1,
    'RITUALISM': 1
}

df['Crime_Severity_Score'] = df['Primary Type'].map(severity_map)

In [72]:
df['Crime_Severity_Score'].value_counts()

Crime_Severity_Score
2    331778
3    160117
1      9099
4      3575
Name: count, dtype: int64

In [73]:
df['Crime_Severity_Score'].isnull().sum()

np.int64(0)

In [74]:
df[df['Crime_Severity_Score'].isnull()]['Primary Type'].value_counts()

Series([], Name: count, dtype: int64)

In [75]:
def season(month):
    if month in [12,1,2]:
        return "Winter"
    elif month in [3,4,5]:
        return "Spring"
    elif month in [6,7,8]:
        return "Summer"
    else:
        return "Fall"

df["Season"] = df["Month"].apply(season)

In [76]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location', 'Hour', 'Day', 'Day_of_Week', 'Month', 'Is_Weekend',
       'Crime_Severity_Score', 'Season'],
      dtype='object')

In [77]:
df["Day"].unique()

array([ 9,  2, 24, 22, 20,  8,  4, 21, 26, 28, 10,  6,  7, 18, 11, 17, 30,
        1, 12,  3, 14, 27, 13, 31, 16, 15, 19, 25, 23,  5, 29],
      dtype=int32)

In [78]:
df["Month"].unique()

array([ 5,  3, 12,  9,  1, 11,  7,  4, 10,  8,  6,  2], dtype=int32)

In [79]:
print(df["Latitude"].min(), df["Latitude"].max())
print(df["Longitude"].min(), df["Longitude"].max())

df[df["Latitude"] == df["Latitude"].max()]

36.619446395 42.022558955
-91.686565684 -87.524529465

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Latitude,Longitude,Location,Hour,Day,Day_of_Week,Month,Is_Weekend,Crime_Severity_Score,Season
137951,13786802,JJ195253,2025-03-26 10:00:00,077XX N SHERIDAN RD,1156,DECEPTIVE PRACTICE,ATTEMPT - FINANCIAL IDENTITY THEFT,APARTMENT,0,0,...,42.022559,-87.666221,"(42.022558955, -87.666221029)",10,26,2,3,0,2,Spring

In [80]:
df = df[
    (df["Latitude"].between(41.7, 42.05)) &
    (df["Longitude"].between(-87.95, -87.5))
]

In [81]:
df.shape

(480122, 29)

In [82]:
cols_to_drop = [
    "ID",
    "Case Number",
    "Block",
    "IUCR",
    "FBI Code",
    "X Coordinate",
    "Y Coordinate",
    "Updated On",
    "Location",
    "Description",
    "Location Description",
    "Beat",
    "Ward",
    "Date"
]
df.drop(columns=cols_to_drop, inplace=True)
df.shape

(480122, 15)

In [84]:
df.columns

Index(['Primary Type', 'Arrest', 'Domestic', 'District', 'Community Area',
       'Year', 'Latitude', 'Longitude', 'Hour', 'Day', 'Day_of_Week', 'Month',
       'Is_Weekend', 'Crime_Severity_Score', 'Season'],
      dtype='object')

In [ ]:
# df.to_csv("../data/crime_500k_cleaned.csv", index=False)